# Setup
title:               Junaid Rahim
tagline:             ''
description:         "Hey, I'm Junaid. <br> I'm currently building systems and data pipelines at <a href='https://atlan.com'>Atlan</a>."
url:                 https://junaidrahim.dev
baseurl:             ''
paginate:            20
permalink:           pretty

# About/contact
author:
  name:              Junaid Rahim
  url:               https://twitter.com/junaidrahxm
  email:             junaidrahim5a@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-twitter-plugin

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
