# Setup
title:               Junaid Rahim
tagline:             'hehe'
description:         'Yo tis is my bio'
url:                 https://junaidrahim.in
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Junaid Rahim
  url:               https://twitter.com/junaidrahxm
  email:             junaidrahim5a@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
